/*
|--------------------------------------------------------------------------
| api.js -- server routes
|--------------------------------------------------------------------------
|
| This file defines the routes for your server.
|
*/

const express = require("express");

// import models so we can interact with the database
const User = require("./models/user");
const Comment = require("./models/comment");
const Exercise = require("./models/exercise");
const Workout = require("./models/workout");

// import authentication library
const auth = require("./auth");

// api endpoints: all these paths will be prefixed with "/api/"
const router = express.Router();

//initialize socket
const socketManager = require("./server-socket");

router.post("/login", auth.login);
router.post("/logout", auth.logout);
router.get("/whoami", (req, res) => {
  if (!req.user) {
    // not logged in
    return res.send({});
  }

  res.send(req.user);
});

router.post("/initsocket", (req, res) => {
  // do nothing if user not logged in
  if (req.user)
    socketManager.addUser(req.user, socketManager.getSocketFromSocketID(req.body.socketid));
  res.send({});
});

// |------------------------------|
// | write your API methods below!|
// |------------------------------|

router.post("/workout", auth.ensureLoggedIn, (req, res) => {
  const newWorkout = new Workout({
    creator_id: req.user._id,
    creator_name: req.user.name,
  });
  newWorkout.save().then((workout) => {
    res.send(workout);
  });
});

router.get("/workouts", (req, res) => {
  Workout.find({}).then((workouts) => res.send(workouts));
});

router.post("/comment", (req, res) => {
  const newComment = new Comment({
    creator_id: req.user._id,
    creator_name: req.user.name,
    parent: req.body.parent, // links to the _id of a parent workout (_id is an autogenerated field by Mongoose).
    content: req.body.content,
  });
  newComment.save().then((comment) => {
    res.send(comment);
  });
});

router.get("/comments", (req, res) => {
  Comment.find({ parent: req.query.parent }).then((comments) => res.send(comments));
});

router.post("/like", (req, res) => {
  Workout.findById(req.body.postId).then((workout) => {
    workout.likes = workout.likes + req.body.like;
    workout.save();
    /* workout.likes = workout.likes + req.query.like;
    workout.save(); */
  });
});

// anything else falls to this "not found" case
router.all("*", (req, res) => {
  console.log(`API route not found: ${req.method} ${req.url}`);
  res.status(404).send({ msg: "API route not found" });
});

module.exports = router;
