name: Deploy FitLink

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Create .env file
        run: |
          echo "MONGO_SRV=${{ secrets.MONGO_SRV }}" >> .env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      # Build frontend
      - name: Build React frontend
        run: |
          npm run build
          echo "Frontend build completed"

      - name: Prepare deployment files
        run: |
          mkdir -p build_temp/frontend
          mkdir -p build_temp/backend

          # Copy frontend files
          cp -R client/dist/* build_temp/frontend/

          # Copy backend files
          cp -R server build_temp/backend/
          cp package.json build_temp/
          cp package-lock.json build_temp/
          cp .env build_temp/

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy to server
        run: |
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete build_temp/frontend/ root@fitlink.live:/var/www/fitlink/frontend/
          rsync -avz -e "ssh -o StrictHostKeyChecking=no" --delete build_temp/backend/ root@fitlink.live:/var/www/fitlink/backend/

      - name: Run post-deployment commands
        run: |
          ssh -o StrictHostKeyChecking=no root@fitlink.live '
            set -e
            
            # Backend setup
            echo "Setting up backend..."
            cd /var/www/fitlink/backend
            npm install --production
            
            # Restart backend service with PM2
            echo "Restarting backend service..."
            pm2 restart fitlink-backend || pm2 start server/server.js --name "fitlink-backend"
            
            # Frontend setup
            echo "Setting up frontend..."
            cd /var/www/fitlink/frontend
            npm install --production
            
            # Restart frontend service with PM2
            echo "Restarting frontend service..."
            pm2 restart fitlink-frontend || pm2 start client/dist/bundle.js --name "fitlink-frontend"
            
            # Reload Nginx
            echo "Reloading Nginx..."
            sudo systemctl reload nginx
            
            echo "Deployment completed successfully"
          '

      - name: Cleanup
        if: always()
        run: rm -rf ~/.ssh
