name: Deploy FitLink

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Frontend for Production
        run: npm run build

      - name: Create .env file
        run: |
          echo "MONGO_SRV=${{ secrets.MONGO_SRV }}" > .env
          echo "SESSION_SECRET=${{ secrets.SESSION_SECRET }}" >> .env
          echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env

      - name: List files in current directory
        run: ls -la

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/aws.pem
          chmod 600 ~/.ssh/aws.pem
          chmod 700 ~/.ssh

      - name: Update known hosts
        run: |
          ssh-keyscan -H ec2-3-84-34-77.compute-1.amazonaws.com >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy Backend to Server
        run: |
          rsync -avz -e "ssh -i ~/.ssh/aws.pem -o StrictHostKeyChecking=no" \
            --delete server/ ec2-user@ec2-3-84-34-77.compute-1.amazonaws.com:/var/www/fitlink/server/

          rsync -avz -e "ssh -i ~/.ssh/aws.pem -o StrictHostKeyChecking=no" \
            --delete package.json package-lock.json .env \
            ec2-user@ec2-3-84-34-77.compute-1.amazonaws.com:/var/www/fitlink/server/

          rsync -avz -e "ssh -i ~/.ssh/aws.pem -o StrictHostKeyChecking=no" \
            --delete node_modules/ ec2-user@ec2-3-84-34-77.compute-1.amazonaws.com:/var/www/fitlink/server/node_modules/

      - name: Deploy Frontend to Server
        run: |
          echo "Deploying frontend..."
          rsync -avz -e "ssh -i ~/.ssh/aws.pem -o StrictHostKeyChecking=no" \
            --delete client/dist/ ec2-user@ec2-3-84-34-77.compute-1.amazonaws.com:/var/www/fitlink/frontend/

      - name: Run post-deployment commands
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ec2-3-84-34-77.compute-1.amazonaws.com '
            set -e

            # server setup
            echo "Setting up server..."
            cd /var/www/fitlink/server

            # Restart server service with PM2
            echo "Restarting server service..."
            pm2 restart fitlink-server || pm2 start npm --name "fitlink-server" -- run start

            # Reload Nginx
            echo "Reloading Nginx..."
            sudo systemctl reload nginx

            echo "Deployment completed successfully"
          '

      - name: Cleanup
        if: always()
        run: rm -rf ~/.ssh
